services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      QOREID_CLIENT_ID: ${QOREID_CLIENT_ID:-}
      QOREID_API_KEY: ${QOREID_API_KEY:-}
      QOREID_BASE_URL: ${QOREID_BASE_URL:-https://api.qoreid.com/v1}
    restart: unless-stopped
